fx_version 'cerulean'
game 'gta5'
author 'Q4D#7967'
description 'Nghề Nhặt rác theo nhóm'
license 'Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License'
    shared_script 'config.lua'
    client_script 'client.lua'
    server_script 'server.lua'
lua54 'yes'