Citizen.CreateThread(function()
    SetWeaponDamageModifier(GetHashKey('WEAPON_UNARMED'), 0.1)
    SetWeaponDamageModifier(GetHashKey('WEAPON_NIGHTSTICK'), 0.8)
    -- Melee
    SetWeaponDamageModifier(GetHashKey('WEAPON_FLASHLIGHT'), 0.0)
    SetWeaponDamageModifier(GetHashKey('WEAPON_HAMMER'), 0.2)
    SetWeaponDamageModifier(GetHashKey('WEAPON_SWITCHBLADE'), 0.2)
    SetWeaponDamageModifier(GetHashKey('WEAPON_WRENCH'), 0.2)
    SetWeaponDamageModifier(GetHashKey('WEAPON_BREAD'), 1)
    SetWeaponDamageModifier(GetHashKey('WEAPON_KATANA4'), 0.4)
    SetWeaponDamageModifier(GetHashKey('WEAPON_KATANA3'), 0.4)
    SetWeaponDamageModifier(GetHashKey('WEAPON_KATANA2'), 0.4)
    SetWeaponDamageModifier(GetHashKey('WEAPON_KATANA'), 0.4)
    SetWeaponDamageModifier(GetHashKey('WEAPON_PENETRATOR'), 0.01)
    SetWeaponDamageModifier(GetHashKey('WEAPON_GOLFCLUB'), 0.35)
    SetWeaponDamageModifier(GetHashKey('WEAPON_HATCHET'), 0.3)
    SetWeaponDamageModifier(GetHashKey('WEAPON_MACHETE'), 0.3)
    SetWeaponDamageModifier(GetHashKey('WEAPON_BAT'), 0.35)
    SetWeaponDamageModifier(GetHashKey('WEAPON_CROWBAR'), 0.35)
    SetWeaponDamageModifier(GetHashKey('WEAPON_DAGGER'), 0.30)
    SetWeaponDamageModifier(GetHashKey('WEAPON_PISTOL'), 0.5)
    SetWeaponDamageModifier(GetHashKey('WEAPON_BATTLEAXE'), 0.45)
    SetWeaponDamageModifier(GetHashKey('WEAPON_POOLCUE'), 0.40)
    SetWeaponDamageModifier(GetHashKey('WEAPON_KNIFE'), 0.30)
end)